[default.extend-words]
iif = "iif"
odf = "odf"
ono = "ono"

[files]
extend-exclude = ["depends-on.json", "go.mod", "results.html", "cmd/certsuite/claim/compare/testdata", "docs/assets/images/*.svg", "*.js"]
