---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - certsuite.yaml

# Uncomment the next line (namespace transformer) to deploy all the certsuite related
# resources in a different namespace.
# namespace: my-custom-ns-name

# Uncomment the next lines so each resource's name have a custom prefix and/or suffix appended.
# namePrefix: myprefix-
# nameSuffix: -mysuffix

# Uncomment the next lines (patches) in order to launch the certsuite pod with a different
# test cases labels filter/expr. The following example changes the labels to "preflight".
# patches:
#   - target:
#       version: v1
#       kind: Pod
#       name: certsuite
#     patch: |
#       - op: replace
#         path: /spec/containers/0/args/1
#         value: |
#           ./certsuite.sh -l 'preflight' ; sleep inf

# Uncomment the next lines (patches) in order to allow intrusive TCs to run.
# patches:
#   - target:
#       version: v1
#       kind: Pod
#       name: certsuite
#     patch: |
#       - op: replace
#         path: /spec/containers/0/env/1
#         value: |
#           ./certsuite.sh -l '!affiliated-certification-container-is-certified-digest && !access-control-security-context' --non-intrusive=false ; sleep inf
