---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plain-http
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plain-http
      tls-test: target
  template:
    metadata:
      labels:
        app: plain-http
        tls-test: target
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: plain-http-svc
spec:
  selector:
    app: plain-http
  ports:
    - port: 80
      targetPort: 8080
