targetNameSpaces:
  - name: tnf
#DEPRECATED
#targetPodLabels:
#  - prefix: test-network-function.com
#    name: generic
#    value: target
podsUnderTestLabels:
  - "test-network-function.com/generic: target"
# deprecated operator label ("test-network-function.com/operator:"") still configured by default, no need to add it here
operatorsUnderTestLabels:
  - "test-network-function.com/operator1:new" 
targetCrdFilters:
  - nameSuffix: "group1.test.com"
    scalable: false
  - nameSuffix: "test-network-function.com"
    scalable: false
  - nameSuffix: "tutorial.my.domain"
    scalable: true 
managedDeployments:
  - name: jack
managedStatefulsets:
  - name: jack
certifiedcontainerinfo:
  - name: rocketchat/rocketchat
    repository: registry.connect.redhat.com
    tag: 0.56.0-1 # optional, "latest" assumed if empty
    digest: # if set, takes precedence over tag. e.g. "sha256:aa34453a6417f8f76423ffd2cf874e9c4a1a5451ac872b78dc636ab54a0ebbc3"
  - name: rocketchat/rocketchat
    repository: registry.connect.redhat.com
    tag: 0.56.0-1
    digest: sha256:03f7f2499233a302351821d6f78f0e813c3f749258184f4133144558097c57b0
checkDiscoveredContainerCertificationStatus: false
acceptedKernelTaints:
  - module: vboxsf
  - module: vboxguest
skipScalingTestDeployments:
  - name: deployment1
    namespace: tnf
skipScalingTestStatefulsets:
  - name: statefulset1
    namespace: tnf
skipHelmChartList:
  - name: coredns
validProtocolNames:
  - "http3"
  - "sctp"
servicesignorelist:
  - "hazelcast-platform-controller-manager-service"
  - "hazelcast-platform-webhook-service"
  - "new-pro-controller-manager-metrics-service"
collectorAppEndPoint: ""
executedBy: "default-executed-by"
partnerName: "test-partner-name"
collectorAppPassword: "test-password"