name: build

on:
  pull_request:
    types: [ closed ]

permissions:
  contents: read

jobs:
  do-not-merge:
    if: ${{ contains(github.event.*.labels.*.name, 'do not merge') }}
    name: Prevent Merging
    runs-on: ubuntu-22.04
    steps:
      - name: Check for label
        run: |
          echo "Pull request is labeled as 'do not merge'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1
  build:
    if: github.event.pull_request.merged == true
    name: Run Tests
    runs-on: ubuntu-22.04
    steps:

      - name: Set up Go 1.22
        uses: actions/setup-go@cdcb36043654635271a94b9a6d1392de5bb323a7 # v5.0.1
        with:
          go-version: 1.22.3

      - name: Check out code into the Go module directory
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6

      - name: Run Tests
        run: make test
        env:
          SHELL: /bin/bash

  close_job:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-22.04
    steps:
      - run: |
          echo PR #${{ github.event.number }} has been closed without being merged
