name: Update RHCOS version mapping

on:
  # Triggers the workflow every day
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-certification:
    name: Update offline mapping of RHCOS to OCP version
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash        

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4
        with:
          ref: main

      - name: Execute `make update-rhcos-versions`
        run: make update-rhcos-versions

      - name: Set up Go 1.22
        uses: actions/setup-go@v5
        with:
          go-version: 1.22.2

        # This prevents any failures due to the updated rhcos_versions_map file from
        # making it into the PR phase.
      - name: Run unit tests
        run: make test

      - name: Create PR
        uses: peter-evans/create-pull-request@v6
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_CERTIFIED_DB_TOKEN }}
        with:
          commit-message: Update RHCOS to OCP version map
          title: Update RHCOS to OCP version map
          body: |
            - RHCOS version map update
          branch: update-rhcos-map
