name: Update RHCOS version mapping

on:
  # Triggers the workflow every day
  schedule:
    - cron: "0 0 * * *"
  # pull_request:
  #   branches:
  #     - main
  workflow_dispatch:
permissions:
  contents: read

jobs:
  update-certification:
    if: github.repository_owner == 'redhat-best-practices-for-k8s'
    permissions:
      contents: write  # for peter-evans/create-pull-request to create branch
      pull-requests: write  # for peter-evans/create-pull-request to create a PR
    name: Update offline mapping of RHCOS to OCP version
    runs-on: ubuntu-24.04
    env:
      SHELL: /bin/bash        

    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          ref: main

      - name: Check and install 'oc' OpenShift client
        run: |
          if ! command -v oc &> /dev/null; then
            echo "'oc' not found, installing..."
            TEMP_DIR=$(mktemp -d)
            curl -Lo $TEMP_DIR/openshift-client-linux.tar.gz https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux.tar.gz
            tar -xvf $TEMP_DIR/openshift-client-linux.tar.gz -C $TEMP_DIR
            sudo mv $TEMP_DIR/oc $TEMP_DIR/kubectl /usr/local/bin/
            rm -rf $TEMP_DIR
          else
            echo "'oc' is already installed."
          fi

      - name: Execute `make update-rhcos-versions`
        run: make update-rhcos-versions

      - name: Set up Go
        uses: actions/setup-go@4dc6199c7b1a012772edbd06daecab0f50c9053c # v6.1.0
        with:
          go-version-file: go.mod

        # This prevents any failures due to the updated rhcos_versions_map file from
        # making it into the PR phase.
      - name: Run unit tests
        run: make test

      - name: Create PR
        uses: peter-evans/create-pull-request@98357b18bf14b5342f975ff684046ec3b2a07725 # v8.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_CERTIFIED_DB_TOKEN }}
        with:
          commit-message: Update RHCOS to OCP version map
          title: Update RHCOS to OCP version map
          body: |
            - RHCOS version map update
          branch: update-rhcos-map
