name: Update RHCOS version mapping

on:
  # Triggers the workflow every day
  schedule:
    - cron: "0 0 * * *"
jobs:
  update-certification:
    name: Update offline mapping of RHCOS to OCP version
    runs-on: ubuntu-22.04
    env:
      SHELL: /bin/bash        

    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Execute `make update-rhcos-versions`
        run: make update-rhcos-versions

      - name: Create PR
        uses: peter-evans/create-pull-request@v4
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_CERTIFIED_DB_TOKEN }}
        with:
          commit-message: Update RHCOS to OCP version map
          title: Update RHCOS to OCP version map
          body: |
            - RHCOS version map update
          branch: update-rhcos-map
