name: Upload release assets 

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-24.04
    steps:
      - name: Check out code
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Build Certsuite binary (x86_64)
        env:
          SHELL: /bin/bash
        run: |
          make build
          tar -cvzf certsuite-${GITHUB_REF_NAME}-x86_64.tar.gz certsuite
          rm certsuite

      - name: Build Certsuite binary (ARM 64)
        env:
          SHELL: /bin/bash
        run: |
          make build-darwin-arm64
          tar -cvzf certsuite-${GITHUB_REF_NAME}-arm64.tar.gz certsuite
          rm certsuite

      - name: Upload Certsuite binaries
        env:
          SHELL: /bin/bash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${GITHUB_REF_NAME} certsuite-${GITHUB_REF_NAME}-x86_64.tar.gz certsuite-${GITHUB_REF_NAME}-arm64.tar.gz
