name: Upload release assets 

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  upload-release-assets:
    name: Upload release assets
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Go
        uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34 # v5.3.0
        with:
          go-version-file: go.mod

      - name: Build Certsuite binary (x86_64)
        env:
          SHELL: /bin/bash
        run: |
          make build
          tar -cvzf certsuite-${GITHUB_REF_NAME}-x86_64.tar.gz certsuite
          rm certsuite

      - name: Build Certsuite binary (ARM 64)
        env:
          SHELL: /bin/bash
        run: |
          make build-darwin-arm64
          tar -cvzf certsuite-${GITHUB_REF_NAME}-arm64.tar.gz certsuite
          rm certsuite

      - name: Upload Certsuite binaries
        env:
          SHELL: /bin/bash
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release upload ${GITHUB_REF_NAME} certsuite-${GITHUB_REF_NAME}-x86_64.tar.gz certsuite-${GITHUB_REF_NAME}-arm64.tar.gz
